language: ruby
rvm:
  - 2.5.8
  - 2.6.6
  - 2.7.2
gemfile:
  - gemfiles/5.2.gemfile
  - gemfiles/6.0.gemfile
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database has_config_test;' -U postgres
script:
  - bundle exec rake test
sudo: false
