language: ruby
rvm:
  - 2.3.7
  - 2.4.4
  - 2.5.1
gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile
addons:
  postgresql: '9.6'
before_script:
  - psql -c 'create database has_config_test;' -U postgres
script:
  - bundle exec rake test
sudo: false
