language: ruby
rvm:
  - 2.1
  - 2.2
  - 2.3
gemfile:
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
matrix:
  exclude:
    - rvm: 2.1
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.2
      gemfile: gemfiles/5.0.gemfile
addons:
  postgresql: '9.4'
before_script:
  - psql -c 'create database has_config_test;' -U postgres
script:
  - bundle exec rake test
sudo: false
