name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PGPASSWORD: postgres
  POSTGRES_HOST: localhost

jobs:
  tests:
    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - gemfile: '6.1'
            ruby: '3.0'

          - gemfile: '6.1'
            ruby: '3.1'

          - gemfile: '6.1'
            ruby: '3.2'

          - gemfile: '7.0'
            ruby: '3.0'

          - gemfile: '7.0'
            ruby: '3.1'

          - gemfile: '7.0'
            ruby: '3.2'

          - gemfile: '7.0'
            ruby: '3.3'

          - gemfile: '7.1'
            ruby: '3.0'

          - gemfile: '7.1'
            ruby: '3.1'

          - gemfile: '7.1'
            ruby: '3.2'

          - gemfile: '7.1'
            ruby: '3.3'

    name: rails ${{ matrix.gemfile }}, ruby ${{ matrix.ruby }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: false

    - name: Bundle install
      run: |
        bundle config set gemfile "${GITHUB_WORKSPACE}/gemfiles/${{ matrix.gemfile }}.gemfile"
        bundle install --jobs 4 --retry 3

    - name: Create DB
      run: |
        psql -c 'create database has_config_test;' -U postgres -h localhost

    - name: Run tests
      run: |
        bundle exec rake test
